//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hymnal.XF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hymnal.XF.Resources.Languages.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adventist Hymnal.
        /// </summary>
        public static string AdventistHymnal {
            get {
                return ResourceManager.GetString("AdventistHymnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Build.
        /// </summary>
        public static string AppBuild {
            get {
                return ResourceManager.GetString("AppBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Version.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Hymn Page.
        /// </summary>
        public static string AutomationHymnPageClose {
            get {
                return ResourceManager.GetString("AutomationHymnPageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn lyrics.
        /// </summary>
        public static string AutomationHymnPageContent {
            get {
                return ResourceManager.GetString("AutomationHymnPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add or remove from favorites.
        /// </summary>
        public static string AutomationHymnPageFavorite {
            get {
                return ResourceManager.GetString("AutomationHymnPageFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn is not in favorites.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsInFavoritesFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn is in favorites.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsInFavoritesTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn is not playing.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsPlayingFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn is playing.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsPlayingTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open piano sheet.
        /// </summary>
        public static string AutomationHymnPagePianoSheet {
            get {
                return ResourceManager.GetString("AutomationHymnPagePianoSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play or Pause music.
        /// </summary>
        public static string AutomationHymnPagePlayer {
            get {
                return ResourceManager.GetString("AutomationHymnPagePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share hymn.
        /// </summary>
        public static string AutomationHymnPageShare {
            get {
                return ResourceManager.GetString("AutomationHymnPageShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn title.
        /// </summary>
        public static string AutomationHymnPageTitle {
            get {
                return ResourceManager.GetString("AutomationHymnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change to Alphabetical order.
        /// </summary>
        public static string AutomationIndexPageAlphabeticalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageAlphabeticalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change to Numerical order.
        /// </summary>
        public static string AutomationIndexPageNumericalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageNumericalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change to Thematic index.
        /// </summary>
        public static string AutomationIndexPageThematicIndex {
            get {
                return ResourceManager.GetString("AutomationIndexPageThematicIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter hymn number.
        /// </summary>
        public static string AutomationNumberPageEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Below there is a button to open the hymn.
        /// </summary>
        public static string AutomationNumberPageHelpTextEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageHelpTextEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open hymn.
        /// </summary>
        public static string AutomationNumberPageOpenHymnButton {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenHymnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Records page.
        /// </summary>
        public static string AutomationNumberPageOpenRecords {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Search page.
        /// </summary>
        public static string AutomationNumberPageOpenSearch {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change hymnal.
        /// </summary>
        public static string AutomationSettingsPageChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Below check current version.
        /// </summary>
        public static string AutomationSettingsPageHelpTextChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageHelpTextChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background image appearance.
        /// </summary>
        public static string BackgroundImageAppearance {
            get {
                return ResourceManager.GetString("BackgroundImageAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display and typography.
        /// </summary>
        public static string DisplayAndTypography {
            get {
                return ResourceManager.GetString("DisplayAndTypography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We had a problem.
        /// </summary>
        public static string Error_WeHadAProblem {
            get {
                return ResourceManager.GetString("Error_WeHadAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Generic_Open {
            get {
                return ResourceManager.GetString("Generic_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumental.
        /// </summary>
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumental or sung.
        /// </summary>
        public static string InstrumentalOrSung {
            get {
                return ResourceManager.GetString("InstrumentalOrSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep screen always on.
        /// </summary>
        public static string KeepScreenAlwaysOn {
            get {
                return ResourceManager.GetString("KeepScreenAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no Internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search .....
        /// </summary>
        public static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support this app.
        /// </summary>
        public static string SettingsPage_SupportProject {
            get {
                return ResourceManager.GetString("SettingsPage_SupportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sung.
        /// </summary>
        public static string Sung {
            get {
                return ResourceManager.GetString("Sung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versions and languages.
        /// </summary>
        public static string VersionsAndLanguages {
            get {
                return ResourceManager.GetString("VersionsAndLanguages", resourceCulture);
            }
        }
    }
}
