//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hymnal.XF.Resources.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Hymnal.XF.Resources.Languages.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AdventistHymnal {
            get {
                return ResourceManager.GetString("AdventistHymnal", resourceCulture);
            }
        }
        
        public static string AppBuild {
            get {
                return ResourceManager.GetString("AppBuild", resourceCulture);
            }
        }
        
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageClose {
            get {
                return ResourceManager.GetString("AutomationHymnPageClose", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageContent {
            get {
                return ResourceManager.GetString("AutomationHymnPageContent", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageFavorite {
            get {
                return ResourceManager.GetString("AutomationHymnPageFavorite", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageHelpTextIsInFavoritesFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesFalse", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageHelpTextIsInFavoritesTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesTrue", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageHelpTextIsPlayingFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingFalse", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageHelpTextIsPlayingTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingTrue", resourceCulture);
            }
        }
        
        public static string AutomationHymnPagePianoSheet {
            get {
                return ResourceManager.GetString("AutomationHymnPagePianoSheet", resourceCulture);
            }
        }
        
        public static string AutomationHymnPagePlayer {
            get {
                return ResourceManager.GetString("AutomationHymnPagePlayer", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageShare {
            get {
                return ResourceManager.GetString("AutomationHymnPageShare", resourceCulture);
            }
        }
        
        public static string AutomationHymnPageTitle {
            get {
                return ResourceManager.GetString("AutomationHymnPageTitle", resourceCulture);
            }
        }
        
        public static string AutomationIndexPageAlphabeticalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageAlphabeticalOrder", resourceCulture);
            }
        }
        
        public static string AutomationIndexPageNumericalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageNumericalOrder", resourceCulture);
            }
        }
        
        public static string AutomationIndexPageThematicIndex {
            get {
                return ResourceManager.GetString("AutomationIndexPageThematicIndex", resourceCulture);
            }
        }
        
        public static string AutomationNumberPageEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageEntry", resourceCulture);
            }
        }
        
        public static string AutomationNumberPageHelpTextEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageHelpTextEntry", resourceCulture);
            }
        }
        
        public static string AutomationNumberPageOpenHymnButton {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenHymnButton", resourceCulture);
            }
        }
        
        public static string AutomationNumberPageOpenRecords {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenRecords", resourceCulture);
            }
        }
        
        public static string AutomationNumberPageOpenSearch {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenSearch", resourceCulture);
            }
        }
        
        public static string AutomationSettingsPageChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageChangeHymn", resourceCulture);
            }
        }
        
        public static string AutomationSettingsPageHelpTextChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageHelpTextChangeHymn", resourceCulture);
            }
        }
        
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        public static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        public static string DisplayAndTypography {
            get {
                return ResourceManager.GetString("DisplayAndTypography", resourceCulture);
            }
        }
        
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        public static string InstrumentalOrSung {
            get {
                return ResourceManager.GetString("InstrumentalOrSung", resourceCulture);
            }
        }
        
        public static string KeepScreenAlwaysOn {
            get {
                return ResourceManager.GetString("KeepScreenAlwaysOn", resourceCulture);
            }
        }
        
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        public static string Generic_Open {
            get {
                return ResourceManager.GetString("Generic_Open", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Sung {
            get {
                return ResourceManager.GetString("Sung", resourceCulture);
            }
        }
        
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        public static string VersionsAndLanguages {
            get {
                return ResourceManager.GetString("VersionsAndLanguages", resourceCulture);
            }
        }
        
        public static string Error_WeHadAProblem {
            get {
                return ResourceManager.GetString("Error_WeHadAProblem", resourceCulture);
            }
        }
    }
}
