//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hymnal.XF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hymnal.XF.Resources.Languages.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventist Hymnal.
        /// </summary>
        public static string AdventistHymnal {
            get {
                return ResourceManager.GetString("AdventistHymnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Build.
        /// </summary>
        public static string AppBuild {
            get {
                return ResourceManager.GetString("AppBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Hymn Page.
        /// </summary>
        public static string AutomationHymnPageClose {
            get {
                return ResourceManager.GetString("AutomationHymnPageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn lyrics.
        /// </summary>
        public static string AutomationHymnPageContent {
            get {
                return ResourceManager.GetString("AutomationHymnPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove from favorites.
        /// </summary>
        public static string AutomationHymnPageFavorite {
            get {
                return ResourceManager.GetString("AutomationHymnPageFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn is not in favorites.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsInFavoritesFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn is in favorites.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsInFavoritesTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsInFavoritesTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn is not playing.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsPlayingFalse {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn is playing.
        /// </summary>
        public static string AutomationHymnPageHelpTextIsPlayingTrue {
            get {
                return ResourceManager.GetString("AutomationHymnPageHelpTextIsPlayingTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open piano sheet.
        /// </summary>
        public static string AutomationHymnPagePianoSheet {
            get {
                return ResourceManager.GetString("AutomationHymnPagePianoSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or Pause music.
        /// </summary>
        public static string AutomationHymnPagePlayer {
            get {
                return ResourceManager.GetString("AutomationHymnPagePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share hymn.
        /// </summary>
        public static string AutomationHymnPageShare {
            get {
                return ResourceManager.GetString("AutomationHymnPageShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hymn title.
        /// </summary>
        public static string AutomationHymnPageTitle {
            get {
                return ResourceManager.GetString("AutomationHymnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Alphabetical order.
        /// </summary>
        public static string AutomationIndexPageAlphabeticalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageAlphabeticalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Numerical order.
        /// </summary>
        public static string AutomationIndexPageNumericalOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageNumericalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Thematic index.
        /// </summary>
        public static string AutomationIndexPageThematicIndex {
            get {
                return ResourceManager.GetString("AutomationIndexPageThematicIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hymn number.
        /// </summary>
        public static string AutomationNumberPageEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below there is a button to open the hymn.
        /// </summary>
        public static string AutomationNumberPageHelpTextEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageHelpTextEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open hymn.
        /// </summary>
        public static string AutomationNumberPageOpenHymnButton {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenHymnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Records page.
        /// </summary>
        public static string AutomationNumberPageOpenRecords {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Search page.
        /// </summary>
        public static string AutomationNumberPageOpenSearch {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change hymnal.
        /// </summary>
        public static string AutomationSettingsPageChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below check current version.
        /// </summary>
        public static string AutomationSettingsPageHelpTextChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageHelpTextChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image appearance.
        /// </summary>
        public static string BackgroundImageAppearance {
            get {
                return ResourceManager.GetString("BackgroundImageAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and typography.
        /// </summary>
        public static string DisplayAndTypography {
            get {
                return ResourceManager.GetString("DisplayAndTypography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had a problem.
        /// </summary>
        public static string Error_WeHadAProblem {
            get {
                return ResourceManager.GetString("Error_WeHadAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Generic_Close {
            get {
                return ResourceManager.GetString("Generic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Generic_Ok {
            get {
                return ResourceManager.GetString("Generic_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Generic_Open {
            get {
                return ResourceManager.GetString("Generic_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental or sung.
        /// </summary>
        public static string InstrumentalOrSung {
            get {
                return ResourceManager.GetString("InstrumentalOrSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep screen always on.
        /// </summary>
        public static string KeepScreenAlwaysOn {
            get {
                return ResourceManager.GetString("KeepScreenAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search .....
        /// </summary>
        public static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support this app.
        /// </summary>
        public static string SettingsPage_SupportProject {
            get {
                return ResourceManager.GetString("SettingsPage_SupportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sung.
        /// </summary>
        public static string Sung {
            get {
                return ResourceManager.GetString("Sung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions and languages.
        /// </summary>
        public static string VersionsAndLanguages {
            get {
                return ResourceManager.GetString("VersionsAndLanguages", resourceCulture);
            }
        }
    }
}
