// This file has been autogenerated from a class added in the UI designer.

using System;
using Hymnal.Core.ViewModels;
using MvvmCross.Platforms.Ios.Views;
using Foundation;
using UIKit;

namespace Hymnal.Native.iOS.Views
{
	[MvxFromStoryboard("Main")]
	public partial class SearchCollectionViewController : MvxCollectionViewController<SearchViewModel>
	{
		public SearchCollectionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
