// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Hymnal.Native.iOS.Views
{
	public partial class IndexTableViewController : UITableViewController
	{
		public IndexTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
