// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Hymnal.iOS.Views
{
	public partial class SearchTableViewController : UITableViewController
	{
		public SearchTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
