//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hymnal.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hymnal.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adventist Hymnal.
        /// </summary>
        internal static string AdventistHymnal {
            get {
                return ResourceManager.GetString("AdventistHymnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Build.
        /// </summary>
        internal static string AppBuild {
            get {
                return ResourceManager.GetString("AppBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Version.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Hymn Page.
        /// </summary>
        internal static string AutomationHymnPageClose {
            get {
                return ResourceManager.GetString("AutomationHymnPageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn lyrics.
        /// </summary>
        internal static string AutomationHymnPageContent {
            get {
                return ResourceManager.GetString("AutomationHymnPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add or remove from favorites.
        /// </summary>
        internal static string AutomationHymnPageFavorite {
            get {
                return ResourceManager.GetString("AutomationHymnPageFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open piano sheet.
        /// </summary>
        internal static string AutomationHymnPagePianoSheet {
            get {
                return ResourceManager.GetString("AutomationHymnPagePianoSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play or Pause music.
        /// </summary>
        internal static string AutomationHymnPagePlayer {
            get {
                return ResourceManager.GetString("AutomationHymnPagePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share hymn.
        /// </summary>
        internal static string AutomationHymnPageShare {
            get {
                return ResourceManager.GetString("AutomationHymnPageShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hymn title.
        /// </summary>
        internal static string AutomationHymnPageTitle {
            get {
                return ResourceManager.GetString("AutomationHymnPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alphabetic order.
        /// </summary>
        internal static string AutomationIndexPageAlphabeticOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageAlphabeticOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numeric order.
        /// </summary>
        internal static string AutomationIndexPageNumericOrder {
            get {
                return ResourceManager.GetString("AutomationIndexPageNumericOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thematic index.
        /// </summary>
        internal static string AutomationIndexPageThematicIndex {
            get {
                return ResourceManager.GetString("AutomationIndexPageThematicIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry hymn number.
        /// </summary>
        internal static string AutomationNumberPageEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Below there is a button to open the hymn.
        /// </summary>
        internal static string AutomationNumberPageHelpTextEntry {
            get {
                return ResourceManager.GetString("AutomationNumberPageHelpTextEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open hymn.
        /// </summary>
        internal static string AutomationNumberPageOpenHymnButton {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenHymnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Records page.
        /// </summary>
        internal static string AutomationNumberPageOpenRecords {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Search page.
        /// </summary>
        internal static string AutomationNumberPageOpenSearch {
            get {
                return ResourceManager.GetString("AutomationNumberPageOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change hymn language.
        /// </summary>
        internal static string AutomationSettingsPageChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Below check current version.
        /// </summary>
        internal static string AutomationSettingsPageHelpTextChangeHymn {
            get {
                return ResourceManager.GetString("AutomationSettingsPageHelpTextChangeHymn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contribute.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Amount.
        /// </summary>
        internal static string CustomAmount {
            get {
                return ResourceManager.GetString("CustomAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developing.
        /// </summary>
        internal static string Developing {
            get {
                return ResourceManager.GetString("Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display and typography.
        /// </summary>
        internal static string DisplayAndTypography {
            get {
                return ResourceManager.GetString("DisplayAndTypography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donations.
        /// </summary>
        internal static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GitHub.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumental.
        /// </summary>
        internal static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumental or sung.
        /// </summary>
        internal static string InstrumentalOrSung {
            get {
                return ResourceManager.GetString("InstrumentalOrSung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep screen always on.
        /// </summary>
        internal static string KeepScreenAlwaysOn {
            get {
                return ResourceManager.GetString("KeepScreenAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no Internet connection.
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search .....
        /// </summary>
        internal static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sung.
        /// </summary>
        internal static string Sung {
            get {
                return ResourceManager.GetString("Sung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tip.
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versions and languages.
        /// </summary>
        internal static string VersionsAndLanguages {
            get {
                return ResourceManager.GetString("VersionsAndLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We had a problem.
        /// </summary>
        internal static string WeHadAProblem {
            get {
                return ResourceManager.GetString("WeHadAProblem", resourceCulture);
            }
        }
    }
}
